# -*- coding: utf-8 -*-
"""Assignment-6 Final Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18NFZdPadcgN93H5kaRCCyR0N03Cc_QZf
"""

#Assignment-6
#Final_Project
#Day-6
#Date:06/07/2021
#Amal V.V
#amalvv2000cit@gmail.com

"""**TIC TAC TOE**"""

theBoard = {'7': ' ' , '8': ' ' , '9': ' ' ,
            '4': ' ' , '5': ' ' , '6': ' ' ,
            '1': ' ' , '2': ' ' , '3': ' ' }

board_keys = []

for key in theBoard:
    board_keys.append(key)

def printBoard(board):
    print(board['7'] + '|' + board['8'] + '|' + board['9'])
    print('-+-+-')
    print(board['4'] + '|' + board['5'] + '|' + board['6'])
    print('-+-+-')
    print(board['1'] + '|' + board['2'] + '|' + board['3'])

def game():

    player = 'X'
    count = 0


    for i in range(10):
        printBoard(theBoard)
        print("It's your turn ....." + player + "...Move to which box?")

        move = input()        

        if theBoard[move] == ' ':
            theBoard[move] = player
            count += 1
        else:
            print("That box is already filled.\n Move to which box?")
            continue

        if count >= 5:
            if theBoard['7'] == theBoard['8'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")                
                break
            elif theBoard['4'] == theBoard['5'] == theBoard['6'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break
            elif theBoard['1'] == theBoard['2'] == theBoard['3'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break
            elif theBoard['1'] == theBoard['4'] == theBoard['7'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break
            elif theBoard['2'] == theBoard['5'] == theBoard['8'] != ' ': 
                printBoard(theBoard)
                print("\nGAME OVER.\n")                
                print(" **** " +player + " WON ****")
                break
            elif theBoard['3'] == theBoard['6'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break 
            elif theBoard['7'] == theBoard['5'] == theBoard['3'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break
            elif theBoard['1'] == theBoard['5'] == theBoard['9'] != ' ': 
                printBoard(theBoard)
                print("\n..GAME OVER..\n")                
                print(" **** " +player + " WON ****")
                break 

        if count == 9:
            print("\n..GAME OVER..\n")                
            print("..DRAW MATCH..3")

        if player =='X':
            player = 'O'
        else:
            player = 'X'        
    
    restart = input("Do want to play Again?(Y/N)")
    if restart == "y" or restart == "Y":  
        for key in board_keys:
            theBoard[key] = " "

        game()

if __name__ == "__main__":
    game()